### ISSUE TITLE
pcc.php missclick

### ISSUE THREAD

**Issue by Re4DeR** [andreas-glaser/poloniex-php-client#2]
public function cancelLoanOffer(int $oderNumber): Result {
        return $this->sendTradingRequest([
            'command'    => 'cancelLoanOffer',
            'oderNumber' => $oderNumber,
        ]);
    }

shuld be 

    public function cancelLoanOffer(int $oderNumber): Result {
        return $this->sendTradingRequest([
            'command'    => 'cancelLoanOffer',
            '**orderNumber**' => $oderNumber,
        ]);
    }

**Comment by andreas-glaser** [comment]
Thanks for reporting that. 
https://github.com/andreas-glaser/poloniex-php-client/commit/5ede4648a746be7d0cb6cbc6ae503e92f351eb9a
