### ISSUE TITLE
cancelLoanOffer

### ISSUE THREAD

**Issue by Re4DeR** [andreas-glaser/poloniex-php-client#3]
If I try cancelLoanOffer api return missing parametr error. I founded that API should need two parametres "currencyPair" and "orderNumber".

**Comment by andreas-glaser** [comment]
Hmm okay, looks like an issue in their documentation. It reads:

> cancelLoanOffer
> 
> Cancels a loan offer specified by the "orderNumber" POST parameter. Sample output:
> 
> {"success":1,"message":"Loan offer canceled."}

Can you confirm that this is the case?

**Comment by Re4DeR** [comment]
I really dont know. when I used cancelLoanOffer with only orderNumber parameter it SOMETIME doesnt work. 
now I am using cancelLoanOffer with currency parameter and it is ok 

```php

    /**
     * @param     $currency
     * @param int $oderNumber
     * @return \AndreasGlaser\PPC\Result
     * @author Andreas Glaser
     */
    public function cancelLoanOffer($currency, int $oderNumber): Result {
        return $this->sendTradingRequest([
            'command'      => 'cancelLoanOffer',
            'currency' => $currency,
            'orderNumber'  => $oderNumber,
        ]);
    }
```
